 /*


  JAVASCRIPT / TYPESCRIPT
 JS

  -Operações matematicas básicas
  -Operações condicionais
  -Booleanos(treu ou false)
 */

  //console.log("Code Runner rodando com sucesso")

/*
  //Calcular a porcentagem de um numeor
  function porcentagem(numero, por)
  {
    return (numero/100) * por;

  }
  console.log(porcentagem(1000, 60));
*/
 //Criar uma função que execute a soma de dois valores
/*
 function soma (valor1, valor2){
  return valor1 + valor2
 }
 console.log(soma(20.5, 30.5));
*/
 // Criar uma função que exiba soma, subtração, multiplicação e divisão de dois numeros.
/*
 function operacoes (valor1, valor2, valor3, valor4) {
  console.log(`A soma entre ${valor1} e ${valor2} é ${valor3=(valor1 + valor2)   } sabia que se você multiplicar ${valor1/10} e ${(valor2/10) * 3}  da ${valor4=((valor1/10) * ((valor2/10) * 3))} tambem? muito legal ne?! e se vc juntar ${valor3} e ${valor4} e  separar 5% da soma sera ${((valor3 + valor4)/100) * 5}` ); 
  console.log(`a subtração entre  ${valor1} e ${valor2} é ${valor1 - valor2}`);
  }
operacoes(50, 100);
*/
//Criar uma função que verifique se um numeor inteiro é divisivel por tres e retorne como true ou false
/*
//(true= verdadeiro)
//(false=falso)
function divisivel(numeroint){
  //condicionais em JS

  if( numeroint % 3 == 0) {
    return true
  } else {
    return false
  }
}
console.log(divisivel(30));
*/
//Criar um mecanismo que exiba se um usuario esta logado, ou não
/*
 autenticado = true;
 switch (autenticado){
  case true:
    console.log( "O usuario esta LOGADO");
    break;
    case false:
      console.log(" O usuario não está logado");
 }
 */
//FAzer uma conversão nde celsius para fahrenheit
/*
function cpf(n) {
  return n * 1.8 + 32;
}
console.log(cpf(20))

// COnversão de fahrenheit para celsius
function fpc(n) {
  return(n-32)/1.8;
}
console.log(fpc(68))
*/